[package]
name = "example-basic"
version = "0.0.0"
authors = ["philipahlberg <philipahlberg@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
camo = { path = "../../camo", features = ["derive"] }
