name: cargo-fmt
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add rustfmt
      - run: cargo fmt -v --all -- --check
