name: cargo-test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo test --lib --verbose
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo test --test integration_tests --verbose
