name: cargo-publish
on:
  release:
    types: [created]
jobs:
  publish:
    strategy:
      matrix:
        crate: [camo, camo-derive, camo-typescript]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ${{ matrix.crate }}
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
