name: push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  unit_tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: cargo --version
      - run: cargo test --lib --no-run
      - run: cargo test --lib

  integration_tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: cargo --version
      - run: cargo test --test integration_tests --no-run
      - run: cargo test --test integration_tests

  fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: cargo --version
      - run: cargo fmt -v --all -- --check

  clippy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: cargo --version
      - run: cargo clippy --all-features -- -D warnings
