name: release

on:
  release:
    types: [created]

jobs:
  tests:
    uses: ./.github/workflows/run_tests.yml

  publish:
    runs-on: ubuntu-22.04
    needs: [tests]
    steps:
      - uses: actions/checkout@v2
      - run: cargo --version
      - run: cargo test
      - run: cargo publish
        working-directory: ./camo
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
      - run: cargo publish
        working-directory: ./camo-derive
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
      - run: cargo publish
        working-directory: ./camo-typescript
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
