name: schedule

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

jobs:
  audit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: cargo --version
      - run: cargo install cargo-audit --locked --version ^0.17 --features vendored-openssl
      - run: cargo audit
        continue-on-error: true

  outdated:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: cargo --version
      - run: cargo install cargo-outdated --locked --version ^0.11 --features vendored-openssl
      - run: cargo outdated --exit-code 1
        continue-on-error: true

